# 本地测试
version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-practice
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
  redis:
    image: redis
    container_name: rabbitmq-practice-redis
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - mynetwork
networks:
  mynetwork: