spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456

    # publisher-confirms: true 改配置已经弃用
    publisher-confirm-type: correlated
    publisher-returns: true #开启发送失败回退

    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 0  #连接池中的最小空闲连接
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1ms  #最大阻塞等待时间(负数表示没限制)
    connect-timeout: 30000ms  #连接超时时间（毫秒）